service: S3Cross

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: "arn:aws:logs:*:*:*"
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: "arn:aws:s3:::*/"
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource: "arn:aws:s3:::*/*"
    - Effect: "Allow"
      Action:
        - "s3:ListObjects"
      Resource: "*"

package:
  exclude:
    - venv/**

custom:
  stage: "${opt:stage, self:provider.stage}"

functions:
  runner:
    handler: handler.runner
    memorySize: 128
    timeout: 60
    environment: ${file(env-${self:custom.stage}.yml)}

